services:
  devcontainer-msvc:
    build:
      dockerfile: Dockerfile
    ports:
      - 22
    working_dir: &workdir C:/workspaces/${PROJECT_NAME-}
    volumes:
      - type: bind
        source: ..
        target: *workdir
      - type: bind
        source: ~/.ssh
        target: C:/Users/User/.ssh
      - type: volume
        source: devcontainer-msvc-appdata
        target: C:/Users/User/AppData

volumes:
  devcontainer-msvc-appdata:
