services:
  devcontainer-x11-cpp:
    volumes:
      - type: volume
        target: /home/user/.vscode-server
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "sudo chown user:user ~/.vscode-server; while sleep 1000; do :; done"
