services:
  devcontainer-cpp:
    build:
      dockerfile: ${IMAGE_VARIANT}.Dockerfile
      network: host
      pull: true
    network_mode: host
    working_dir: &workdir /workspaces/${PROJECT_NAME-}
    volumes:
      - type: bind
        source: ..
        target: *workdir
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  devcontainer-cpp-x11:
    extends:
      service: devcontainer-cpp
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ~/.Xauthority
        target: /home/user/.Xauthority
